/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spacemathgame;

import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author butkowb
 */
public class signIn extends javax.swing.JFrame {

    /**
     * Creates new form signIn
     */
    public signIn() {
        initComponents();

        ErrorCheck.setEditable(false);
        //       setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signinword = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JToggleButton();
        btnSignUp = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        usernameEnter = new javax.swing.JTextField();
        passwordEnter = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ErrorCheck = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signinword.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        signinword.setText("           SIGN IN TO PLAY");
        signinword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                signinwordKeyPressed(evt);
            }
        });

        btnSignIn.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        btnSignUp.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Don't have an account? Sign Up below!");

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setText("Username:");

        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setText("Password:");

        usernameEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameEnterActionPerformed(evt);
            }
        });

        ErrorCheck.setColumns(20);
        ErrorCheck.setRows(5);
        jScrollPane1.setViewportView(ErrorCheck);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username)
                    .addComponent(password))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordEnter)
                    .addComponent(usernameEnter, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSignUp)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSignIn)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(25, 25, 25))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(signinword, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signinword, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username)
                            .addComponent(usernameEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password)
                            .addComponent(passwordEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignIn))
                .addGap(27, 27, 27)
                .addComponent(btnSignUp)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameEnterActionPerformed


    }//GEN-LAST:event_usernameEnterActionPerformed

    private void signinwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signinwordKeyPressed

    }//GEN-LAST:event_signinwordKeyPressed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed

        String username1 = usernameEnter.getText();
        String password1 = passwordEnter.getText();
int user =0;
        Users[] all = new Users[1000];

        Scanner userCheck1;

        try {
            userCheck1 = new Scanner(new File("storeUsers.txt")).useDelimiter("#");

            int helper = 0;
            while (userCheck1.hasNextLine()) {
                Scanner userCheck = new Scanner(userCheck1.nextLine()).useDelimiter("#");
                String name = userCheck.next();
                String surname = userCheck.next();
                String username = userCheck.next();
                String password = userCheck.next();
                String email = userCheck.next();
                int gold = userCheck.nextInt();
                all[helper] = new Users(name, surname, username, password, email,gold);
                helper++;
                userCheck.close();
            }
            userCheck1.close();
            boolean correct = false;
            boolean usernameUsed = false;
            for (int a = 0; a < helper; a++) {
                if (all[a].getUsername().equalsIgnoreCase(username1)) {
                    usernameUsed = true;
                    if (all[a].getPassword().equalsIgnoreCase(password1)) {
                        correct = true;
                        user = a;
                        a = helper;
                    }

                }
            }

            if (correct) {
                MainMenu help = new MainMenu();
                help.setResizable(false);
                help.setVisible(true);
              
                
                
                //Save current user to first in text file
                try {
                    
                    
                    
                    PrintWriter file = new PrintWriter(new FileWriter("storeUsers.txt",false));
                    file.println(all[user].toString());
                    for (int b = 0; b < helper; b++) {
                        if(b != user){
                            
                    file.println(all[b].toString());
                        }
                    }
                    file.close();
                    
                } catch (IOException ex) {
                    Logger.getLogger(signIn.class.getName()).log(Level.SEVERE, null, ex);
                }
                  dispose();

            } else if (!usernameUsed) {

                ErrorCheck.setText("That username does not exist");
            } else if (usernameUsed) {

                ErrorCheck.setText("The password is incorrect");
            }

        } catch (FileNotFoundException ex) {
        }

    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        signUp helper = new signUp();
        helper.setResizable(false);
        helper.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ErrorCheck;
    private javax.swing.JToggleButton btnSignIn;
    private javax.swing.JToggleButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordEnter;
    private javax.swing.JLabel signinword;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameEnter;
    // End of variables declaration//GEN-END:variables
}
